source "https://rubygems.org"

gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem "sinatra-contrib"
gem "pg"
gem "rspec"
gem 'rack-test'
gem "rack-reducer"
gem "will_paginate", "~> 3.1.0" 
gem "pry"
gem "database_cleaner"
gem "factory_bot"
gem "shoulda-matchers"